ARG BASE_VERSION="1.22.7"

FROM ghcr.io/gbraad-devenv/ubi9-gotoolset/dotfiles:${BASE_VERSION}

USER root

RUN cd /tmp \
    && curl -fL https://code.visualstudio.com/sha/download?build=stable\&os=cli-alpine-x64 -o code-cli.tar.gz \
    && tar zxvf code-cli.tar.gz \
    && mv code /usr/bin/code \
    && rm -f code-cli.tar.gz

# systemd
COPY assets/code-serveweb@.service /etc/systemd/system/
COPY assets/code-tunnel@.service /etc/systemd/system/

RUN systemctl enable tailscaled

ENTRYPOINT ["/sbin/init"]
